### ISSUE TITLE
feature request: send custom headers

### ISSUE THREAD

**Issue by tablecell** [AlexWayfer/flame#189]
like 
```
 headers["Content-Type"] = "application/json"
 headers["Access-Control-Allow-Origin"] = "*"

```

**Comment by AlexWayfer** [comment]
Hello.

Check please this wiki: https://github.com/AlexWayfer/flame/wiki/Controllers#built-in

> There are also Hash-like `request.headers`, `response.headers`, `cookies` and `session`.

**Comment by tablecell** [comment]
```

class IndexController < Flame::Controller 
  def test
          response.headers   "Content-Type: application/json"
          body   '{"name":"jack"}'
   end 
 end
```
 ArgumentError - wrong number of arguments (given 1, expected 0):

**Comment by AlexWayfer** [comment]
> ```
> 
> class IndexController < Flame::Controller 
>   def test
>           response.headers   "Content-Type: application/json"
>           body   '{"name":"jack"}'
>    end 
>  end
> ```
> 
> ArgumentError - wrong number of arguments (given 1, expected 0):

Flame is Rack-based framework: https://rubydoc.info/gems/rack/Rack/Response#headers-instance_method

Headers are like Hash.

```ruby
response.headers["Content-Type"] = "application/json"
```

**Comment by tablecell** [comment]
`response.headers["Content-Type"]` works
thanks for your help

**Comment by AlexWayfer** [comment]
I think I'll add more documentation there.
