### ISSUE TITLE
(Flame::Errors::RouteExtraArgumentsError)

### ISSUE THREAD

**Issue by tablecell** [AlexWayfer/flame#275]
app.rb 
```ruby

Dir[File.join(".", "controllers/*.rb")].each { |f| require f }
class App < Flame::Application
  mount ProjectsController do      
      get '/category/:cat' , :projectslist  # for url  /projects/category/11
  end
  ..
```
controllers\projects_controller.rb
```ruby
class ProjectsController < Flame::Controller

def  projectslist  

 puts   params

end 
```
visit   http://localhost:9292/projects/category/11
got err 
 Action 'ProjectsController#projects' has no required arguments [:cat] (Flame::Errors::RouteExtraArgumentsError)

Is flame support  named route params    ?

**Comment by AlexWayfer** [comment]
> Is flame support named route params ?

Yep.

If you define `'/category/:cat'` — Flame expects `def projectslist(cat)`.
