### ISSUE TITLE
(Flame::Errors::RouteExtraArgumentsError)

### ISSUE THREAD

**Issue by tablecell** [AlexWayfer/flame#276]
app.rb 
```ruby

Dir[File.join(".", "controllers/*.rb")].each { |f| require f }
class App < Flame::Application
  mount ProjectsController do      
      get '/category/:cat' , :projectslist  # for url  /projects/category/11
  end
  ...
end
```
controllers\projects_controller.rb
```ruby
class ProjectsController < Flame::Controller

  def  projectslist  

        puts   params

  end 
end 
```
visit   http://localhost:9292/projects/category/11
got err 
 Action 'ProjectsController#projects' has no required arguments [:cat] (Flame::Errors::RouteExtraArgumentsError)

Is flame support  named route params    ?

**Comment by AlexWayfer** [comment]
Please, read this wiki: https://github.com/AlexWayfer/flame/wiki/Mounting

If you want a path param — you have to define it as a method argument.

Also there can be optional path params (as an argument with default value).

So, just write `def projectslist(cat)`.
