### ISSUE TITLE
Query params from root Hash-argument for `path_to`

### ISSUE THREAD

**Issue by AlexWayfer** [AlexWayfer/flame#38]
Now:

```ruby
# request.path => '/en/2?foo=bar'

# params => { id: 2, locale: 'en', foo: 'bar' }

path_to :show, params.merge(params: request.params.merge(new_arg: 'value'))
# => '/en/2?foo=bar&new_arg=value
```

Expected:

```ruby
path_to :action, params.merge(new_arg: 'value')
```

**Comment by AlexWayfer** [comment]
Be careful with [`Flame::Flash#extract_flashes`](https://github.com/AlexWayfer/flame-flash/blob/23f7349/lib/flame/flash.rb#L48).

**Comment by snuggs** [comment]
```ruby
path_to :show, params.merge(params: ...
```
wouldn't this give `params.params...` within `:show` action?

**Comment by AlexWayfer** [comment]
> AlexWayfer pardon my ignorance of the library. I'm still learning.

No problem.

> wouldn't this give params.params... within :show action?

I didn't understand the question.

`params` is a regular `Hash`, it doesn't have `#params` method.

**Comment by snuggs** [comment]
@AlexWayfer 
```ruby
params.merge(params: request.params.merge(new_arg: 'value'))
```
Perhaps been staring at Javascript too long but shouldn't be
```ruby
params.merge(request.params.merge(new_arg: 'value'))
```
/cc @brandondees

**Comment by AlexWayfer** [comment]
@snuggs Yes, you're right. It's what about this issue (see "expected"; `params` and `request.params` are almost the same).

Problem:
1. `path_to` receives parameters for actions (`id` for `def show(id)` action) at root Hash, and parameters for query string (`/?foo=bar`) as Hash at `params` key (`params: { foo: :bar }`).
2. `params` contains `request.params` (you can see info about this in the `Rack::Request` documentation) _+_ action's parameters (`id` for `def show(id)`. 

So, there is detailed example:

```ruby
def edit(id)
  p params # => { foo: 'bar', id: 2 }
  path_to :edit, id: 2, params: { foo: 'bar' } # => '/edit/2?foo=bar'
end
```

That should be changed to be more intuitive.

**Comment by snuggs** [comment]
I see now @AlexWayfer
