### ISSUE TITLE
handle more erorrs with server_error

### ISSUE THREAD

**Issue by JelF** [AlexWayfer/flame#57]
When rendering a view SyntaxError can be raised and it will not be handled by server_error because it is not inherited from StandardError.

I think best solution is to cacth Exception and then re-raise it only if it is whitelisted.

**Comment by AlexWayfer** [comment]
Thanks!

> I think best solution is to cacth Exception and then re-raise it only if it is whitelisted.

1. https://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby
2. https://robots.thoughtbot.com/rescue-standarderror-not-exception
3. https://andycroll.com/ruby/rescue-specific-errors-avoid-standarderror-do-not-rescue-exception/

I think rescued exceptions should be white-listed (like `SyntaxError`). But, if there is syntax error in the application Ruby code, not template, you'll get `server_error` in an infinity loop, until you stop the server or restart with fix, as I can understand.

Or no: you possible can't send (and rescue) errors in a code with incorrect syntax.

I'll think and test some cases.
